---
abstract: 'testing whether some value is valid as (Moose|Mouse)::Meta::TypeConstraint'
author:
  - 'Keiji Yoshimi <walf443 at gmail dot com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-TypeConstraints
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Data::Dumper: 0
  Mouse::Util::TypeConstraints: 0
  Scalar::Util: 0
  Test::Builder: 0
  Test::More: 0.98
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/walf443/p5-test-type_constraints.git
version: 0.01
